coverage:
  status:
    project:
      default:
        target: 70%
        threshold: 0%
      dotnet:
        target: 70%
        threshold: 0%
        flags:
          - dotnet
      typescript:
        target: 70%
        threshold: 0%
        flags:
          - typescript
    patch:
      default:
        target: 70%
