<Project>
  <PropertyGroup>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <AnalysisMode Condition="'$(IsTestProject)' != 'true'">All</AnalysisMode>
    <AnalysisMode Condition="'$(IsTestProject)' == 'true'">Recommended</AnalysisMode>
  </PropertyGroup>

  <ItemGroup Condition="'$(IsTestProject)' != 'true'">
    <PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="5.3.0" PrivateAssets="all" />
  </ItemGroup>
</Project>
