import globals from 'globals';
import security from 'eslint-plugin-security';
import jsdoc from 'eslint-plugin-jsdoc';
import importx from 'eslint-plugin-import-x';
import tseslint from 'typescript-eslint';
import unicorn from 'eslint-plugin-unicorn';
import regexp from 'eslint-plugin-regexp';

const importRules = {
  'import-x/first': 'warn',
  'import-x/newline-after-import': 'warn',
  'import-x/no-duplicates': 'warn',
  'import-x/no-self-import': 'warn',
  'import-x/no-useless-path-segments': 'warn',
  'import-x/order': ['warn', { alphabetize: { order: 'asc' }, 'newlines-between': 'always' }],
};

export default tseslint.config(
  {
    files: ['PromiseModelOnline.Client/wwwroot/js/**/*.mjs'],
    languageOptions: {
      globals: {
        ...globals.browser,
        ...globals.es2021,
        bootstrap: 'readonly',
        signalR: 'readonly',
      },
    },
    plugins: { security, jsdoc, 'import-x': importx, unicorn, regexp },
    rules: {
      ...jsdoc.configs['flat/recommended'].rules,
      ...unicorn.configs.recommended.rules,
      ...regexp.configs['flat/recommended'].rules,
      'unicorn/filename-case': 'off',
      'unicorn/prefer-number-coercion': 'off',
      ...importRules,
      'security/detect-eval-with-expression': 'warn',
      'security/detect-non-literal-fs-filename': 'off',
      'security/detect-non-literal-regexp': 'warn',
      'security/detect-non-literal-require': 'warn',
      'security/detect-possible-timing-attacks': 'warn',
      'security/detect-pseudoRandomBytes': 'warn',
      'security/detect-unsafe-regex': 'warn',
      'no-eval': 'error',
      'no-implied-eval': 'error',
      'no-new-func': 'error',
      'no-undef': 'error',
      'no-unused-vars': ['warn', { args: 'none', caughtErrors: 'none' }],
      'no-constant-binary-expression': 'error',
      'no-constructor-return': 'error',
      'no-promise-executor-return': 'error',
      'no-self-assign': 'warn',
      'no-self-compare': 'warn',
      'no-template-curly-in-string': 'warn',
      'no-unmodified-loop-condition': 'warn',
      'no-unreachable-loop': 'warn',
      'require-atomic-updates': 'off',
      'no-async-promise-executor': 'error',
      'no-await-in-loop': 'warn',
      'prefer-promise-reject-errors': 'warn',
      'prefer-const': 'warn',
      'no-var': 'error',
      'eqeqeq': ['warn', 'smart'],
    },
  },
  {
    files: ['PromiseModelOnline.Client/wwwroot/js/**/*.ts'],
    languageOptions: {
      globals: {
        ...globals.browser,
        ...globals.es2021,
      },
      parser: tseslint.parser,
      parserOptions: { projectService: true },
    },
    plugins: { security, jsdoc, 'import-x': importx, unicorn, regexp, '@typescript-eslint': tseslint.plugin },
    rules: {
      ...jsdoc.configs['flat/recommended'].rules,
      ...unicorn.configs.recommended.rules,
      ...regexp.configs['flat/recommended'].rules,
      'unicorn/filename-case': 'off',
      'unicorn/prefer-number-coercion': 'off',
      ...importRules,
      'import-x/no-cycle': 'warn',
      'security/detect-eval-with-expression': 'warn',
      'security/detect-non-literal-fs-filename': 'off',
      'security/detect-non-literal-regexp': 'warn',
      'security/detect-non-literal-require': 'warn',
      'security/detect-possible-timing-attacks': 'warn',
      'security/detect-pseudoRandomBytes': 'warn',
      'security/detect-unsafe-regex': 'warn',
      'no-eval': 'error',
      'no-implied-eval': 'error',
      'no-new-func': 'error',
      'no-constant-binary-expression': 'error',
      'no-constructor-return': 'error',
      'no-promise-executor-return': 'error',
      'no-self-assign': 'warn',
      'no-self-compare': 'warn',
      'no-template-curly-in-string': 'warn',
      'no-unmodified-loop-condition': 'warn',
      'no-unreachable-loop': 'warn',
      'require-atomic-updates': 'off',
      'no-async-promise-executor': 'error',
      'no-await-in-loop': 'warn',
      'prefer-promise-reject-errors': 'warn',
      'prefer-const': 'warn',
      'no-var': 'error',
      'eqeqeq': ['warn', 'smart'],
      '@typescript-eslint/no-unused-vars': ['warn', { args: 'none', caughtErrors: 'none' }],
      '@typescript-eslint/no-explicit-any': 'off',
      '@typescript-eslint/no-floating-promises': 'error',
    },
  },
);
