http:
  middlewares:
    security-headers:
      headers:
        frameDeny: true
        browserXssFilter: false
        contentTypeNosniff: true
        referrerPolicy: "strict-origin-when-cross-origin"
        customResponseHeaders:
          Cross-Origin-Opener-Policy: "same-origin"
          Cross-Origin-Resource-Policy: "same-origin"
          Permissions-Policy: "camera=(), microphone=(), geolocation=(), payment=(), idle-detection=(), accelerometer=()"
          Strict-Transport-Security: "max-age=31536000; includeSubDomains"
    auth-csp:
      headers:
        customResponseHeaders:
          Content-Security-Policy: "default-src 'none'; script-src 'self'; style-src 'self' 'sha256-WWn0l9kVjXaC+CGcbxP6Zyac31v1Cjkx2VMnFR3uVng='; style-src-attr 'sha256-aqNNdDLnnrDOnTNdkJpYlAxKVJtLt9CtFLklmInuUAE='; img-src 'self' data:; font-src 'self'; connect-src 'self'; manifest-src 'self'; worker-src 'self'; base-uri 'none'; form-action 'self'; frame-ancestors 'none'"
