import { apiGet, apiPost, apiPatch } from '../api.ts';

export const getMoment = (owner: string, project: string, momentSeq: string | number) => apiGet(`/api/projects/${encodeURIComponent(owner)}/${encodeURIComponent(project)}/moments/${momentSeq}`);
export const createMoment = (owner: string, project: string, data: Record<string, unknown>) => apiPost(`/api/projects/${encodeURIComponent(owner)}/${encodeURIComponent(project)}/moments/create`, data);
export const getMyAssignedMoments = () => apiGet('/api/moments/assigned-to-me');
export const assignMomentToStride = (owner: string, project: string, momentSeq: string | number, strideId: string | number | undefined) => apiPatch(`/api/projects/${encodeURIComponent(owner)}/${encodeURIComponent(project)}/moments/${momentSeq}/stride-assignment`, { strideId });
export const updateMomentStatus = (owner: string, project: string, momentSeq: string | number, status: string) => apiPatch(`/api/projects/${encodeURIComponent(owner)}/${encodeURIComponent(project)}/moments/${momentSeq}/status`, { newStatus: status });
export const updateMomentEstimate = (owner: string, project: string, momentSeq: string | number, estimate: string | undefined) => apiPatch(`/api/projects/${encodeURIComponent(owner)}/${encodeURIComponent(project)}/moments/${momentSeq}/estimate`, { estimate });
export const updateMomentType = (owner: string, project: string, momentSeq: string | number, type: string) => apiPatch(`/api/projects/${encodeURIComponent(owner)}/${encodeURIComponent(project)}/moments/${momentSeq}/type`, { newType: type });
export const updateMomentOwner = (owner: string, project: string, momentSeq: string | number, userId: string | number) => apiPatch(`/api/projects/${encodeURIComponent(owner)}/${encodeURIComponent(project)}/moments/${momentSeq}/owner`, { userId });
export const updateMomentDescription = (owner: string, project: string, momentSeq: string | number, description: string) => apiPatch(`/api/projects/${encodeURIComponent(owner)}/${encodeURIComponent(project)}/moments/${momentSeq}/description`, { description });
export const createTask = (owner: string, project: string, momentSeq: string | number, data: Record<string, unknown>) => apiPost(`/api/projects/${encodeURIComponent(owner)}/${encodeURIComponent(project)}/moments/${momentSeq}/tasks`, data);
export const updateTaskCompletion = (owner: string, project: string, momentSeq: string | number, taskId: string | number, isCompleted: boolean) => apiPatch(`/api/projects/${encodeURIComponent(owner)}/${encodeURIComponent(project)}/moments/${momentSeq}/tasks/${taskId}/completion`, { isCompleted });
