using System.ComponentModel.DataAnnotations;

namespace PromiseModelOnline.Auth.ViewModels;

/// <summary>Form data for the reset-password page: token, email, and new password.</summary>
/// <remarks>The token and email are hidden fields pre-populated from the reset-link query string.</remarks>
public class ResetPasswordViewModel
{
    /// <summary>Password-reset token generated by <see cref="Microsoft.AspNetCore.Identity.UserManager{TUser}.GeneratePasswordResetTokenAsync"/>. Required.</summary>
    [Required]
    [StringLength(2048)]
    public string Token { get; set; } = string.Empty;

    /// <summary>The email address of the account to reset. Required, must be a valid email format.</summary>
    [Required]
    [EmailAddress]
    [StringLength(254)]
    public string Email { get; set; } = string.Empty;

    /// <summary>The new password. Required, minimum 6 characters.</summary>
    [Required(ErrorMessage = "New password is required.")]
    [DataType(DataType.Password)]
    [StringLength(100, MinimumLength = 6, ErrorMessage = "Password must be at least 6 characters.")]
    public string Password { get; set; } = string.Empty;

    /// <summary>Confirmation of the new password. Must match <see cref="Password"/>. Required.</summary>
    [Required(ErrorMessage = "Please confirm your new password.")]
    [DataType(DataType.Password)]
    [StringLength(128, MinimumLength = 6)]
    [Compare("Password", ErrorMessage = "Passwords do not match.")]
    public string ConfirmPassword { get; set; } = string.Empty;
}
