---
- name: Destroy Docker Swarm stack
  hosts: vm_host
  tasks:
    - name: Remove Swarm stack
      ansible.builtin.shell:
        cmd: sudo docker stack rm promisemodelonline
      register: stack_rm_result
      ignore_errors: true

    - name: Remove named volumes
      ansible.builtin.shell:
        cmd: sudo docker volume rm mssql-data bff-dp-keys auth-dp-keys umami-db 2>/dev/null; true
      register: volume_rm_result
