pid /tmp/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    server_tokens off;

    limit_req_zone $binary_remote_addr zone=login:10m rate=10r/m;
    limit_req_zone $binary_remote_addr zone=api:10m rate=600r/m;
    limit_req_zone $binary_remote_addr zone=hubs:10m rate=60r/m;
    limit_req_zone $binary_remote_addr zone=token:10m rate=20r/m;
    limit_req_zone $binary_remote_addr zone=register:10m rate=3r/m;
    limit_req_zone $binary_remote_addr zone=account:10m rate=30r/m;
    limit_req_zone $binary_remote_addr zone=verify-email:10m rate=3r/m;
    limit_req_zone $binary_remote_addr zone=external:10m rate=30r/m;

    gzip on;
    gzip_min_length 1024;
    gzip_comp_level 5;
    gzip_buffers 16 8k;
    gzip_types
        text/plain
        text/css
        application/json
        application/javascript
        application/x-javascript
        text/xml
        application/xml
        application/xml+rss
        text/javascript
        image/svg+xml;
    gzip_disable "msie6";
    gzip_vary on;

    limit_req_status 429;

    upstream bff_upstream {
        ip_hash;
        zone bff_upstream 64k;
        server promisemodelonline.bff:8010 resolve;
    }

    resolver 127.0.0.11 valid=30s;

    include /etc/nginx/conf.d/*.conf;
}
