---
all:
  children:
    host_machine:
      hosts:
        localhost:
          ansible_connection: local
    vm_host:
      hosts:
        promisemodel-vm:
          ansible_host: 192.168.122.50
          ansible_user: pmo_admin
          ansible_ssh_private_key_file: ~/.ssh/pmo_vm_key
