name: PromiseModelOnline
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  workflow_dispatch:
jobs:
  BuildAndTest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
              
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x
      
      - name: Add Client CI TLS/SSL CERT & KEY
        shell: bash
        run: |
          echo ${{ vars.CLIENT_CI_CERT }} > PromiseModelOnline.Client/cert.pem
          echo ${{ secrets.CLIENT_CI_KEY }} > PromiseModelOnline.Client/key.pem

      - name: Add API CI TLS/SSL CERT & KEY
        shell: bash
        run: |
          echo ${{ vars.API_CI_CERT }} > PromiseModelOnline.API/cert.pem
          echo ${{ secrets.API_CI_KEY }} > PromiseModelOnline.API/key.pem

      - name: Add AUTH CI TLS/SSL CERT & KEY
        shell: bash
        run: |
          echo ${{ vars.AUTH_CI_CERT }} > PromiseModelOnline.AUTH/cert.pem
          echo ${{ secrets.AUTH_CI_KEY }} > PromiseModelOnline.AUTH/key.pem
      
      - name: Build and Run App Containers
        shell: bash
        run: docker compose up -d

      - name: Push Docker Images to DockerHub
        if: ${{ github.ref == 'refs/heads/main' }}
        shell: bash
        run: |
          docker tag promisemodelonlineapi cherrytree811/promisemodelonlineapi:latest
          docker tag promisemodelonlineclient cherrytree811/promisemodelonlineclient:latest
          docker tag promisemodelonlineauth cherrytree811/promisemodelonlineauth:latest
          docker login -u cherrytree811 -p ${{ secrets.DOCKER_CRED }}
          docker push cherrytree811/promisemodelonlineapi:latest
          docker push cherrytree811/promisemodelonlineclient:latest
          docker push cherrytree811/promisemodelonlineauth:latest
